# Identificación del proyecto
sonar.projectKey=Feelin-Artist-Frontend
sonar.projectName=Feelin Artist Frontend
sonar.projectVersion=1.0

# SonarQube Server
sonar.host.url=http://localhost:9000
sonar.token=sqp_89f5e3a6929fa830ffda9f17444d3c40a25a0c1c

# Código fuente y Pruebas
# Excluimos los tests del análisis de código fuente principal para métricas más limpias
sonar.sources=src,middleware.ts
sonar.exclusions=node_modules/**,.next/**,public/**,**/*.test.ts,**/*.test.tsx,**/__tests__/**

# Definición de pruebas para el cálculo de cobertura
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,**/*.test.tsx,**/*.test.ts

# Archivos TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage Jest/Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info